In [16]:
import numpy as np

In [17]:
np.__version__

'1.16.4'

In [38]:
np.randint(1,high=20,size=21)

AttributeError: module 'numpy' has no attribute 'randint'

In [36]:
np.random.rand(10)

array([0.43572306, 0.78456696, 0.0289544 , 0.43295535, 0.56654448,
       0.8542096 , 0.31320596, 0.09473299, 0.15301534, 0.6159788 ])

In [53]:
 a = np.arange(0,100,10)

In [54]:
print(a)

[ 0 10 20 30 40 50 60 70 80 90]


In [120]:
b = np.arange(0,21,1)

In [121]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [123]:
b = np.delete(b,0)
print(b)
b1 = (b % 2 == 0)
print(b[b1])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]


In [124]:
b2 = (b % 3 == 0)
print(b[b2])

[ 3  6  9 12 15 18]


In [91]:
list(range(0,21))
list.remove(0)

TypeError: descriptor 'remove' requires a 'list' object but received a 'int'

In [ ]:
/*c=[0]
b = np.delete(b,c)*/