In [1]:
import numpy as np
#. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])

In [44]:
np.savez('my_array',array1=array1,array2=array2)
file1=np.load('my_array.npz')
file1.files
print(file1['array1'])
print(file1['array2'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


In [56]:
file2=np.load('multi_array.npz')
file1.files
array3=file2['array1']
array4=file2['array2']
np.savez('my_array',array3=array3,array4=array4)

file3=np.load('multi_array.npz')
file3.files
print(file3['array1'])
print(file3['array2'])
print(file3['array3'])

[0 1 2 3 4 5 6 7 8 9]
[1 2 3]
[0.5788873  0.69082947 0.04922545 0.86517602 0.29889969 0.55285575
 0.69389689 0.49183867 0.8308363  0.06454569]
